### PR TITLE
Fix document link markup

### PR DESCRIPTION
**Pull request by noelleleigh**
This section link is broken in the rendered HTML because of a syntax error I believe.

This should hopefully fix it.

### CODE REVIEW

**Comment by TimothyGu** [comment]
Looks good, thanks! I’ll have to regenerate the HTML files before merging.

**Comment by noelleleigh** [comment]
I tried it, and it made more changes than I expected. Is this normal?

**Comment by TimothyGu** [comment]
Hmm, the "Conformance" section isn't something we should have, and looks like the copyright got changed to CC0 rather than CC BY-SA 4.0. I know there have been quite a few changes in Bikeshed upstream so that might be why.

**Comment by TimothyGu** [comment]
Looks like it's because you don't have Bikeshed installed locally, and the CSSWG server used in https://github.com/TimothyGu/es-howto/blob/7cf1a2fa921ad88c9dbe205001a5955656d0fec1/Makefile#L11-L17 doesn't support some of the features we use like the .include files. Anyway, I just regenerated the files locally and it works. Thanks again!

**Review by TimothyGu — APPROVED** [review]

**Pull request merged**
